export const mockCourses = [
  {
    id: 1,
    title: 'React Fundamentals',
    category: 'Web Development',
    difficulty: 'Beginner',
    progress: 75,
    icon: '⚛️',
    color: '#61dafb',
    description: 'Learn the basics of React and component-based architecture',
    lessons: 12,
    completed: 9,
  },
  {
    id: 2,
    title: 'JavaScript Essentials',
    category: 'Web Development',
    difficulty: 'Beginner',
    progress: 90,
    icon: '🟨',
    color: '#f7df1e',
    description: 'Master JavaScript from the ground up',
    lessons: 15,
    completed: 13,
  },
  {
    id: 3,
    title: 'Data Structures & Algorithms',
    category: 'Computer Science',
    difficulty: 'Intermediate',
    progress: 45,
    icon: '📊',
    color: '#39FF14',
    description: 'Deep dive into DSA with practical examples',
    lessons: 20,
    completed: 9,
  },
  {
    id: 4,
    title: 'Machine Learning Basics',
    category: 'AI & ML',
    difficulty: 'Intermediate',
    progress: 30,
    icon: '🤖',
    color: '#FF6B6B',
    description: 'Introduction to ML algorithms and applications',
    lessons: 18,
    completed: 5,
  },
  {
    id: 5,
    title: 'Advanced CSS & Design',
    category: 'Web Development',
    difficulty: 'Intermediate',
    progress: 60,
    icon: '🎨',
    color: '#FF00FF',
    description: 'Create stunning UI with modern CSS techniques',
    lessons: 14,
    completed: 8,
  },
  {
    id: 6,
    title: 'Node.js & Express',
    category: 'Backend Development',
    difficulty: 'Intermediate',
    progress: 50,
    icon: '🟢',
    color: '#68a063',
    description: 'Build robust server-side applications',
    lessons: 16,
    completed: 8,
  },
  {
    id: 7,
    title: 'Database Design',
    category: 'Database',
    difficulty: 'Intermediate',
    progress: 35,
    icon: '🗄️',
    color: '#00D4FF',
    description: 'SQL, NoSQL, and data modeling best practices',
    lessons: 14,
    completed: 5,
  },
  {
    id: 8,
    title: 'Cloud Computing with AWS',
    category: 'Cloud',
    difficulty: 'Advanced',
    progress: 20,
    icon: '☁️',
    color: '#FFD700',
    description: 'Deploy and scale applications on AWS',
    lessons: 20,
    completed: 4,
  },
  {
    id: 9,
    title: 'DevOps & CI/CD',
    category: 'DevOps',
    difficulty: 'Advanced',
    progress: 25,
    icon: '🔄',
    color: '#FF6B6B',
    description: 'Continuous integration and deployment pipelines',
    lessons: 16,
    completed: 4,
  },
  {
    id: 10,
    title: 'System Design',
    category: 'Engineering',
    difficulty: 'Advanced',
    progress: 40,
    icon: '🏗️',
    color: '#39FF14',
    description: 'Design large-scale distributed systems',
    lessons: 15,
    completed: 6,
  },
  {
    id: 11,
    title: 'Web Security',
    category: 'Security',
    difficulty: 'Advanced',
    progress: 55,
    icon: '🔐',
    color: '#FF00FF',
    description: 'Secure your applications from vulnerabilities',
    lessons: 13,
    completed: 7,
  },
  {
    id: 12,
    title: 'GraphQL API Development',
    category: 'Web Development',
    difficulty: 'Advanced',
    progress: 15,
    icon: '📡',
    color: '#FF00FF',
    description: 'Build modern GraphQL APIs',
    lessons: 12,
    completed: 2,
  },
]

export const mockAchievements = [
  { id: 1, name: 'First Steps', icon: '🎯', description: 'Complete your first course', unlocked: true },
  { id: 2, name: 'Week Warrior', icon: '🔥', description: 'Maintain a 7-day streak', unlocked: true },
  { id: 3, name: 'Course Master', icon: '👑', description: 'Complete 5 courses', unlocked: true },
  { id: 4, name: 'Quiz Champion', icon: '🏆', description: 'Score 100% on quiz', unlocked: true },
  { id: 5, name: 'Night Owl', icon: '🦉', description: 'Study after midnight', unlocked: false },
  { id: 6, name: 'Speedrunner', icon: '⚡', description: 'Complete a course in one day', unlocked: false },
  { id: 7, name: 'Helpful Hero', icon: '🦸', description: 'Help 5 other learners', unlocked: false },
  { id: 8, name: 'Milestone Master', icon: '🎊', description: 'Reach level 10', unlocked: false },
  { id: 9, name: 'Community Star', icon: '⭐', description: 'Get 100 likes on your solution', unlocked: false },
  { id: 10, name: 'Perfect Score', icon: '💯', description: 'Ace all lessons in a course', unlocked: false },
  { id: 11, name: 'Knowledge Keeper', icon: '📚', description: 'Read all course materials', unlocked: false },
  { id: 12, name: 'Legendary Learner', icon: '🌟', description: 'Reach level 50', unlocked: false },
]

export const mockLeaderboard = [
  { id: 1, rank: 1, name: 'CodeNinja', level: 38, totalXP: 95000, streak: 42, avatar: '🥷' },
  { id: 2, rank: 2, name: 'DataWizard', level: 35, totalXP: 87500, streak: 28, avatar: '🧙' },
  { id: 3, rank: 3, name: 'WebMaster', level: 32, totalXP: 80000, streak: 21, avatar: '🕸️' },
  { id: 4, rank: 4, name: 'AlgoKing', level: 31, totalXP: 77500, streak: 19, avatar: '👑' },
  { id: 5, rank: 5, name: 'CloudExplorer', level: 29, totalXP: 72500, streak: 15, avatar: '🚀' },
  { id: 6, rank: 6, name: 'PyPanda', level: 27, totalXP: 67500, streak: 12, avatar: '🐼' },
  { id: 7, rank: 7, name: 'SecurityGuard', level: 26, totalXP: 65000, streak: 10, avatar: '🛡️' },
  { id: 8, rank: 8, name: 'ReactRocket', level: 25, totalXP: 62500, streak: 8, avatar: '🚀' },
  { id: 9, rank: 9, name: 'DevOpsDoctor', level: 24, totalXP: 60000, streak: 6, avatar: '🏥' },
  { id: 10, rank: 10, name: 'DatabaseDiva', level: 22, totalXP: 55000, streak: 5, avatar: '💃' },
  { id: 11, rank: 11, name: 'CSSCreative', level: 20, totalXP: 50000, streak: 3, avatar: '🎨' },
  { id: 12, rank: 12, name: 'Alex Developer', level: 12, totalXP: 5000, streak: 7, avatar: '👨‍💻' },
  { id: 13, rank: 13, name: 'JavaScriptJoe', level: 19, totalXP: 47500, streak: 2, avatar: '🟨' },
  { id: 14, rank: 14, name: 'APIAdventurer', level: 18, totalXP: 45000, streak: 1, avatar: '🧗' },
  { id: 15, rank: 15, name: 'CloudSeeker', level: 16, totalXP: 40000, streak: 0, avatar: '☁️' },
]

export const mockDailyChallenges = [
  { id: 1, title: 'Solve 3 Algorithm Problems', reward: 100, completed: true },
  { id: 2, title: 'Complete 1 React Lesson', reward: 75, completed: false },
  { id: 3, title: 'Review 2 Peer Solutions', reward: 50, completed: false },
]

export const mockUserProgress = [
  { id: 1, course: 'JavaScript Essentials', progress: 90, status: 'In Progress' },
  { id: 2, course: 'React Fundamentals', progress: 75, status: 'In Progress' },
  { id: 3, course: 'CSS & Design', progress: 60, status: 'In Progress' },
  { id: 4, course: 'Data Structures', progress: 45, status: 'In Progress' },
  { id: 5, course: 'Node.js Basics', progress: 50, status: 'In Progress' },
  { id: 6, course: 'HTML Essentials', progress: 100, status: 'Completed' },
]

export const mockSkills = [
  { name: 'Web Development', level: 45 },
  { name: 'Data Structures', level: 60 },
  { name: 'AI & Machine Learning', level: 30 },
  { name: 'Cloud Computing', level: 25 },
  { name: 'DevOps', level: 20 },
  { name: 'Security', level: 55 },
]
